name: Genius-an

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

     
      - name: Print text from index.js
        run: cat dist/index.js
